# Generated by Django 4.1.1 on 2022-09-22 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('domicilio', models.CharField(blank=True, max_length=45, null=True, verbose_name='Domicilio')),
                ('contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('cuit_cuil', models.CharField(max_length=15, verbose_name='CUIT/CUIL')),
            ],
            options={
                'db_table': 'propietarios',
            },
        ),
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre Edificio')),
                ('domicilio', models.CharField(max_length=45, verbose_name='Domicilio')),
                ('cantidad_dptos', models.IntegerField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edificios',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('piso', models.IntegerField(verbose_name='Nro. de Piso')),
                ('numero', models.CharField(max_length=2, verbose_name='Nro. Departamento')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje expensas')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.edificios')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.propietarios')),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
    ]
