# Generated by Django 4.1.1 on 2022-09-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
